spring:
  data:
    mongodb:
      database: JournalApp
      uri: mongodb+srv://aditya:aditya@mongoclustor.glkb7.mongodb.net/?retryWrites=true&w=majority&appName=MongoClustor
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true # auth means it sends credentials for verifying (username,password)
          starttls: # it means data transaction is in encrypted form thats why port - 587 otherwise it would be 525 (start transport layer security)
            enable: true

  main:
    allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /JournalApp

# Severity level - lowest to highest
#trace - lowest
#debug - low
#info - moderate
#warn - high
#error - highest

logging:
  level:
    com:
      journalapp: ERROR

# if we want to modify the internal config and do some things at root level

#logging:
#  level:
#    root: ERROR

# If we want to off the logs of a particular package or class we can follow the below method-

#logging:
#  level:
#    com:
#      journalapp:
#        service:
#          UserService: OFF

weather:
  api:
    key: 3e9a6ab40bf2b2db2965f05cb4e47724
    
python:
  api: http://localhost:5000